version: "2"

services:
  app:
    image: "reservation-service:latest"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/room_reservations
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "80:80"

  db:
    image: 'postgres:14.2-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=room_reservations
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #for test
    ports:
      - "5432:5432"