server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/room_reservations
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always